import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import heroVisual from '../assets/summaries-hero-card.png'
import ringsArt from '../assets/summaries-rings.png'
import glowPink from '../assets/summaries-compare-glow-tr.svg'
import glowPurple from '../assets/summaries-compare-glow-bl.svg'
import glowPurpleDeep from '../assets/summaries-compare-glow-bl2.svg'
import dotCyan from '../assets/summaries-dot-cyan.svg'
import dotOrange from '../assets/summaries-dot-orange.svg'
import dotGreen from '../assets/summaries-dot-green.svg'
import stepLine from '../assets/proposal-step-line.svg'
import byNeedImg from '../assets/proposal-byneed.png'
import footerLogo from '../assets/footer-logo.png'
import Footer from '../components/Footer.jsx'

const HOW_STEPS = [
  {
    title: 'Connect your documents',
    body: 'Reports, meeting minutes, audits, circulars, and other approved material.',
    dot: dotCyan,
    accent: 'cyan',
  },
  {
    title: 'Set your brief',
    body: 'Tell Eveia.AI who the summary is for and what information matters.',
    dot: dotOrange,
    accent: 'orange',
  },
  {
    title: 'Get a source-supported summary',
    body: 'Eveia.AI creates a concise summary with links back to the relevant source.',
    dot: dotGreen,
    accent: 'green',
  },
]

const HELP_POINTS = [
  'Board and committee documents',
  'Audit and consultant reports',
  'Meeting minutes',
  'Policies and circulars',
  'Project and programme updates',
  'Long documents used for handovers',
]

const BY_NEED = [
  {
    title: 'Instant Answers from Data',
    body: 'Your organization already has the information people need.',
    href: '/search',
  },
  {
    title: 'Decision-Ready Reports',
    body: 'Preparing a report often takes more time than writing it.',
    href: '/reports',
  },
  {
    title: 'Create Proposal Faster',
    body: 'Proposal writing often starts with gathering pricing, service information, company.',
    href: '/proposals',
  },
]

function useInView(threshold = 0.2, rootMargin = '0px 0px -40px 0px') {
  const ref = useRef(null)
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true)
          observer.disconnect()
        }
      },
      { threshold, rootMargin }
    )

    if (ref.current) observer.observe(ref.current)
    return () => observer.disconnect()
  }, [threshold, rootMargin])

  return [ref, isVisible]
}

export default function SummariesPage() {
  const [stepsRef, stepsVisible] = useInView(0.15)
  const [stackRef, stackVisible] = useInView(0, '0px 0px 0px 0px')

  return (
    <main className="reports-page search-page summaries-page">
      <div className="reports-hero-wrap">
        <header className="reports-hero">
          <div className="reports-hero-inner">
            <div className="reports-hero-copy">
              <p className="reports-eyebrow">Executive Summaries</p>
              <h1 className="reports-hero-title">
                Turn Long Documents Into Clear Briefs
              </h1>
              <p className="reports-hero-desc">
                Important information is often buried in long reports, meeting
                records, audits, and other documents.
              </p>
              <div className="reports-hero-ctas">
                <a className="btn btn-primary" href="#request-demo">
                  Request a Private Demo
                </a>
                <a className="btn btn-secondary" href="mailto:inquiry@eveia.ai">
                  Send us a message
                </a>
              </div>
              <p className="reports-hero-note">
                Eveia.AI creates concise executive summaries from your approved
                source material, helping leaders and teams quickly understand
                key points without losing the ability to check the original
                information.
              </p>
            </div>
            <div className="summaries-hero-visual">
              <span className="summaries-hero-paper summaries-hero-paper--back" />
              <span className="summaries-hero-paper summaries-hero-paper--mid" />
              <img
                src={heroVisual}
                alt="Q3 board report summary generated by Eveia.AI"
              />
            </div>
          </div>
        </header>
      </div>

      <section className="reports-sources">
        <div className="reports-sources-inner">
          <div className="summaries-how-head">
            <img
              className="summaries-rings"
              src={ringsArt}
              alt=""
              aria-hidden="true"
            />
            <h2 className="reports-sources-title">How it works</h2>
            <p className="reports-sources-desc">
              Turn Long Documents Into Clear, Actionable Summaries
              <br />
              <br />
              Eveia.AI helps your team turn lengthy documents into concise
              summaries that highlight the information that matters most, with
              sources available for review.
            </p>
          </div>
          <div
            ref={stepsRef}
            className={`proposal-steps ${stepsVisible ? 'is-visible' : ''}`}
          >
            {HOW_STEPS.map((step, index) => (
              <div className="proposal-step-wrap" key={step.title}>
                {index > 0 && (
                  <img
                    className="proposal-step-line"
                    src={stepLine}
                    alt=""
                    aria-hidden="true"
                  />
                )}
                <article className={`proposal-step summaries-step summaries-step--${step.accent}`}>
                  <span className="proposal-step-dot">
                    <img src={step.dot} alt="" />
                  </span>
                  <div className="proposal-step-copy">
                    <h3>{step.title}</h3>
                    <p>{step.body}</p>
                  </div>
                </article>
              </div>
            ))}
          </div>
        </div>
      </section>

      <div
        ref={stackRef}
        className={`reports-stack-wrap ${stackVisible ? 'is-visible' : ''}`}
      >
        <div className="reports-stack">
          <section className="reports-how">
            <div className="reports-how-inner">
              <h2 className="reports-how-heading">
                Where it can <span>Help</span>
              </h2>
              <p className="reports-how-lead">
                Use Eveia.AI to summarize the documents your teams regularly
                review, prepare, and share across the organization.
              </p>
              <ul className="reports-how-list">
                {HELP_POINTS.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </section>

          <section className="summaries-compare">
            <img
              className="summaries-compare-glow summaries-compare-glow--tr"
              src={glowPink}
              alt=""
              aria-hidden="true"
            />
            <img
              className="summaries-compare-glow summaries-compare-glow--bl"
              src={glowPurple}
              alt=""
              aria-hidden="true"
            />
            <img
              className="summaries-compare-glow summaries-compare-glow--bl2"
              src={glowPurpleDeep}
              alt=""
              aria-hidden="true"
            />
            <div className="summaries-compare-inner">
              <h2>
                Executive Summaries <span>vs.</span> Eveia.AI
                <br />
                Report Generation
              </h2>
              <p>
                Executive summaries shorten existing material.
                <br />
                Eveia.AI report generation creates a new document from information
                across multiple sources.
                <br />
                <br />
                Both help teams spend less time searching and preparing
                information.
              </p>
              <h3>Built for Review</h3>
              <p>
                Eveia.AI prepares the summary, but people remain responsible for
                reviewing important information and making decisions. Source links
                make it easier to check key points against the original document.
              </p>
            </div>
          </section>

          <section className="reports-amplify">
            <div className="reports-byneed">
              <p className="reports-byneed-label">BY NEED</p>
              <div className="reports-byneed-grid">
                {BY_NEED.map((item) => (
                  <article className="reports-byneed-card" key={item.title}>
                    <img src={byNeedImg} alt="" />
                    <div className="reports-byneed-copy">
                      <h3>{item.title}</h3>
                      <p>{item.body}</p>
                      <Link to={item.href}>Read more →</Link>
                    </div>
                  </article>
                ))}
              </div>
            </div>
          </section>
        </div>
      </div>

      <section className="reports-cta-wrap" id="request-demo">
        <div className="reports-cta">
          <div className="reports-cta-bg" aria-hidden="true">
            <img src={footerLogo} alt="" />
          </div>
          <div className="reports-cta-content">
            <h2 className="reports-cta-heading">Try It With Your Own Documents</h2>
            <p className="reports-cta-desc">
              Bring a long report or document your team regularly needs to
              review. We’ll show you how Eveia.AI can turn it into a concise,
              source-supported summary.
            </p>
            <div className="reports-cta-actions">
              <a className="reports-cta-btn reports-cta-btn--primary" href="mailto:inquiry@eveia.ai">
                Request Demo
              </a>
              <a className="reports-cta-btn" href="mailto:inquiry@eveia.ai">
                Send us a message
              </a>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
